<a href="https://colab.research.google.com/github/Oliz888/Deep-Learning/blob/main/W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Week 1

## Environment configuration

In [1]:
# TENSORFLOW
import tensorflow as tf
print("TENSORFLOW VERSION:",tf.__version__)
print(tf.reduce_sum(tf.random.normal([1000, 1000])))

# PYTORCH
import torch
print("PYTORCH VERSION:",torch.__version__)
x = torch.rand(5, 3)
print(x)

# KERAS
import keras;
print("KERAS VERSION:",keras.__version__)

TENSORFLOW VERSION: 2.15.0
tf.Tensor(-792.73645, shape=(), dtype=float32)
PYTORCH VERSION: 2.3.0+cu121
tensor([[0.7446, 0.4824, 0.3405],
        [0.4268, 0.4943, 0.0353],
        [0.3849, 0.6917, 0.1627],
        [0.8227, 0.3368, 0.3558],
        [0.1746, 0.3258, 0.4497]])
KERAS VERSION: 2.15.0


In [2]:
# GET SYSTEM INFO
# code modified from: https://stackoverflow.com/questions/110362/how-can-i-find-the-current-os-in-python

import platform
import multiprocessing
import sys
import psutil

def linux_distribution():
  try:
    return platform.linux_distribution()
  except:
    return "N/A"

def dist():
  try:
    return platform.dist()
  except:
    return "N/A"

num_cores=multiprocessing.cpu_count()

print("""
Python version: %s
dist: %s
num_cores: %s
linux_distribution: %s
system: %s
machine: %s
platform: %s
uname: %s
version: %s
RAM: %s
""" % (
sys.version.split('\n'),
str(dist()),
num_cores,
linux_distribution(),
platform.system(),
platform.machine(),
platform.platform(),
platform.uname(),
platform.version(),
psutil.virtual_memory().total*10**(-9.)
))

# print('GPU name: ', tf.config.experimental.list_physical_devices('GPU'))


Python version: ['3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]']
dist: N/A
num_cores: 2
linux_distribution: N/A
system: Linux
machine: x86_64
platform: Linux-6.1.85+-x86_64-with-glibc2.35
uname: uname_result(system='Linux', node='cf470fd7f88b', release='6.1.85+', version='#1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024', machine='x86_64')
version: #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
RAM: 13.60943104



In [4]:
import platform
import torch
platform.processor

<function platform.processor()>

In [6]:
print("CUDA available:", torch.cuda.is_available())

CUDA available: True


## Numpy Basics

### Numpy vectors
- NumPy vectors refer specifically to a one-dimensional array.
- Vectors are a subset of arrays, with their shape defined as (n,), simplifying operations for linear algebra and vector computations.

In [7]:
import numpy as np

# NUMPY VECTOR EXAMPLE
x = np.array([1, 2, 3])
print("VECTOR:")
print(x)
print("ndim",x.ndim)
print("shape",x.shape)
print("length",len(x))

VECTOR:
[1 2 3]
ndim 1
shape (3,)
length 3


### Numpy arrays
A NumPy array is a multi-dimensional data structure capable of holding elements of various types

In [8]:
# MATRIX
print("MATRIX:")
A = np.array(
    [
        [1, 1, 0, 1],
        [0, 1, 1, 1],
        [1, 0, 1, 1],
    ]
)
print(A)

print("ATTRIBUTES")
print(A.ndim,"=",len(A.shape))
print(A.shape)
print(A.reshape(2,6))
print(A.reshape(1,12))

MATRIX:
[[1 1 0 1]
 [0 1 1 1]
 [1 0 1 1]]
ATTRIBUTES
2 = 2
(3, 4)
[[1 1 0 1 0 1]
 [1 1 1 0 1 1]]
[[1 1 0 1 0 1 1 1 1 0 1 1]]


### Transpose

In [9]:
print("ORIGINAL:")
print(A)
print("TRANPOSE:")
print(np.transpose(A))

ORIGINAL:
[[1 1 0 1]
 [0 1 1 1]
 [1 0 1 1]]
TRANPOSE:
[[1 0 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]


### Vectors as arrays

In [10]:
# RESHAPE
print("---------")
x=x.reshape(3,1) # --> equivelent to x = np.array([[1], [2], [3]])

print(x)
print("ndim",x.ndim)
print("shape",x.shape)
print("length",len(x))

print("---------")
print("COLUMN VECTOR:")
print(x)
print(x.shape)

print("---------")
print(x.T) # transpose
x = np.array([[1, 2, 3]])
print("ROW VECTOR:")
print(x)
print(x.shape)

---------
[[1]
 [2]
 [3]]
ndim 2
shape (3, 1)
length 3
---------
COLUMN VECTOR:
[[1]
 [2]
 [3]]
(3, 1)
---------
[[1 2 3]]
ROW VECTOR:
[[1 2 3]]
(1, 3)


### Tensors
A tensor is a multi-dimensional array used in mathematics to represent data of higher dimensions than matrices.

In [11]:
print("TENSOR:")
x = np.array(
    [
        [
            [5.0, 78, 2, 34, 0],
            [6, 79, 3, 35, 1],
            [7, 80, 4, 36, 2],
        ],
        [
            [5, 78, 2, 34, 0],
            [6, 79, 3, 35, 1],
            [7, 80, 4, 36, 2],
        ],
        [
            [5, 78, 2, 34, 0],
            [6, 79, 3, 35, 1],
            [7, 80, 4, 36, 2],
        ],
    ]
)
print(x)
print("ndim",x.ndim)
print("shape",x.shape)
print("length",len(x))

TENSOR:
[[[ 5. 78.  2. 34.  0.]
  [ 6. 79.  3. 35.  1.]
  [ 7. 80.  4. 36.  2.]]

 [[ 5. 78.  2. 34.  0.]
  [ 6. 79.  3. 35.  1.]
  [ 7. 80.  4. 36.  2.]]

 [[ 5. 78.  2. 34.  0.]
  [ 6. 79.  3. 35.  1.]
  [ 7. 80.  4. 36.  2.]]]
ndim 3
shape (3, 3, 5)
length 3


### Common operations

In [12]:

xv = np.array([1, 2, 3])           # vector
xr = xv.reshape(1,x.shape[0])      # row vector as array
xc = xv.reshape(x.shape[0],1)      # column vector as array
A = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]]) #matrix

print("xv:\n",xv)
print("xr:\n",xr)
print("xc:\n",xc)
print("A:\n",A)

xv:
 [1 2 3]
xr:
 [[1 2 3]]
xc:
 [[1]
 [2]
 [3]]
A:
 [[1 1 0]
 [0 1 1]
 [1 0 1]]


### Possible additionas

In [13]:
print("ADDITIONS")
for a in [xv,xr,xc,A]:
    for b in [xv,xr,xc,A]:
        print("----------")
        print("a:",a.shape)
        print(a)
        print("b:",b.shape)
        print(b)
        print("a+b")
        print(a+b)

ADDITIONS
----------
a: (3,)
[1 2 3]
b: (3,)
[1 2 3]
a+b
[2 4 6]
----------
a: (3,)
[1 2 3]
b: (1, 3)
[[1 2 3]]
a+b
[[2 4 6]]
----------
a: (3,)
[1 2 3]
b: (3, 1)
[[1]
 [2]
 [3]]
a+b
[[2 3 4]
 [3 4 5]
 [4 5 6]]
----------
a: (3,)
[1 2 3]
b: (3, 3)
[[1 1 0]
 [0 1 1]
 [1 0 1]]
a+b
[[2 3 3]
 [1 3 4]
 [2 2 4]]
----------
a: (1, 3)
[[1 2 3]]
b: (3,)
[1 2 3]
a+b
[[2 4 6]]
----------
a: (1, 3)
[[1 2 3]]
b: (1, 3)
[[1 2 3]]
a+b
[[2 4 6]]
----------
a: (1, 3)
[[1 2 3]]
b: (3, 1)
[[1]
 [2]
 [3]]
a+b
[[2 3 4]
 [3 4 5]
 [4 5 6]]
----------
a: (1, 3)
[[1 2 3]]
b: (3, 3)
[[1 1 0]
 [0 1 1]
 [1 0 1]]
a+b
[[2 3 3]
 [1 3 4]
 [2 2 4]]
----------
a: (3, 1)
[[1]
 [2]
 [3]]
b: (3,)
[1 2 3]
a+b
[[2 3 4]
 [3 4 5]
 [4 5 6]]
----------
a: (3, 1)
[[1]
 [2]
 [3]]
b: (1, 3)
[[1 2 3]]
a+b
[[2 3 4]
 [3 4 5]
 [4 5 6]]
----------
a: (3, 1)
[[1]
 [2]
 [3]]
b: (3, 1)
[[1]
 [2]
 [3]]
a+b
[[2]
 [4]
 [6]]
----------
a: (3, 1)
[[1]
 [2]
 [3]]
b: (3, 3)
[[1 1 0]
 [0 1 1]
 [1 0 1]]
a+b
[[2 2 1]
 [2 3 3]
 [4 3 4]]
----------
a